package com.mh.entity;

import java.util.Date;

public class TBkMatchRmain {
	// 流水号
	// 自增长
	private Integer id;

	private String curtag;

	private Integer matchIndex;

	private Integer matchPage;

	private String timeType;

	private String gid;

	private String matchTime;

	private String league;

	private String gnumH;

	private String gnumC;

	private String teamH;

	private String teamC;

	private String strong;

	private String ratio;

	private String iorRh;

	private String iorRc;

	private String ratioO;

	private String ratioU;

	private String iorOuc;

	private String iorOuh;

	private String iorMh;

	private String iorMc;

	private String iorMn;

	private String strOdd;

	private String strEven;

	private String iorEoo;

	private String iorEoe;

	private String ratioOuho;

	private String ratioOuhu;

	private String iorOuho;

	private String iorOuhu;

	private String ratioOuco;

	private String ratioOucu;

	private String iorOuco;

	private String iorOucu;

	private String eventid;

	private String hot;

	private String centerTv;

	private String play;

	private String more;

	private String gidm;

	private String ismaster;

	private Integer roll;

	private String tmp1;

	private String tmp2;

	private String tmp3;
	
	private Date modifyTime;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCurtag() {
		return curtag;
	}

	
	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	
	public Integer getMatchIndex() {
		return matchIndex;
	}

	public void setMatchIndex(Integer matchIndex) {
		this.matchIndex = matchIndex;
	}

	public Integer getMatchPage() {
		return matchPage;
	}

	
	public void setMatchPage(Integer matchPage) {
		this.matchPage = matchPage;
	}

	
	public String getTimeType() {
		return timeType;
	}

	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	public String getGid() {
		return gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.gid
	 * 
	 * @param gid
	 *            the value for t_bk_match_rmain.gid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.match_time
	 * 
	 * @return the value of t_bk_match_rmain.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMatchTime() {
		return matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.match_time
	 * 
	 * @param matchTime
	 *            the value for t_bk_match_rmain.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchTime(String matchTime) {
		this.matchTime = matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.league
	 * 
	 * @return the value of t_bk_match_rmain.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLeague() {
		return league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.league
	 * 
	 * @param league
	 *            the value for t_bk_match_rmain.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLeague(String league) {
		this.league = league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.gnum_h
	 * 
	 * @return the value of t_bk_match_rmain.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumH() {
		return gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.gnum_h
	 * 
	 * @param gnumH
	 *            the value for t_bk_match_rmain.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumH(String gnumH) {
		this.gnumH = gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.gnum_c
	 * 
	 * @return the value of t_bk_match_rmain.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumC() {
		return gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.gnum_c
	 * 
	 * @param gnumC
	 *            the value for t_bk_match_rmain.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumC(String gnumC) {
		this.gnumC = gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.team_h
	 * 
	 * @return the value of t_bk_match_rmain.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamH() {
		return teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.team_h
	 * 
	 * @param teamH
	 *            the value for t_bk_match_rmain.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamH(String teamH) {
		this.teamH = teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.team_c
	 * 
	 * @return the value of t_bk_match_rmain.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamC() {
		return teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.team_c
	 * 
	 * @param teamC
	 *            the value for t_bk_match_rmain.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamC(String teamC) {
		this.teamC = teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.strong
	 * 
	 * @return the value of t_bk_match_rmain.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrong() {
		return strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.strong
	 * 
	 * @param strong
	 *            the value for t_bk_match_rmain.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrong(String strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio
	 * 
	 * @return the value of t_bk_match_rmain.ratio
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatio() {
		return ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio
	 * 
	 * @param ratio
	 *            the value for t_bk_match_rmain.ratio
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatio(String ratio) {
		this.ratio = ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_RH
	 * 
	 * @return the value of t_bk_match_rmain.ior_RH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorRh() {
		return iorRh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_RH
	 * 
	 * @param iorRh
	 *            the value for t_bk_match_rmain.ior_RH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorRh(String iorRh) {
		this.iorRh = iorRh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_RC
	 * 
	 * @return the value of t_bk_match_rmain.ior_RC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorRc() {
		return iorRc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_RC
	 * 
	 * @param iorRc
	 *            the value for t_bk_match_rmain.ior_RC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorRc(String iorRc) {
		this.iorRc = iorRc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_o
	 * 
	 * @return the value of t_bk_match_rmain.ratio_o
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioO() {
		return ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_o
	 * 
	 * @param ratioO
	 *            the value for t_bk_match_rmain.ratio_o
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioO(String ratioO) {
		this.ratioO = ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_u
	 * 
	 * @return the value of t_bk_match_rmain.ratio_u
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioU() {
		return ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_u
	 * 
	 * @param ratioU
	 *            the value for t_bk_match_rmain.ratio_u
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioU(String ratioU) {
		this.ratioU = ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUH
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuh() {
		return iorOuh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUH
	 * 
	 * @param iorOuh
	 *            the value for t_bk_match_rmain.ior_OUH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuh(String iorOuh) {
		this.iorOuh = iorOuh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUC
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuc() {
		return iorOuc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUC
	 * 
	 * @param iorOuc
	 *            the value for t_bk_match_rmain.ior_OUC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuc(String iorOuc) {
		this.iorOuc = iorOuc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_MH
	 * 
	 * @return the value of t_bk_match_rmain.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMh() {
		return iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_MH
	 * 
	 * @param iorMh
	 *            the value for t_bk_match_rmain.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMh(String iorMh) {
		this.iorMh = iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_MC
	 * 
	 * @return the value of t_bk_match_rmain.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMc() {
		return iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_MC
	 * 
	 * @param iorMc
	 *            the value for t_bk_match_rmain.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMc(String iorMc) {
		this.iorMc = iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_MN
	 * 
	 * @return the value of t_bk_match_rmain.ior_MN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMn() {
		return iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_MN
	 * 
	 * @param iorMn
	 *            the value for t_bk_match_rmain.ior_MN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMn(String iorMn) {
		this.iorMn = iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.str_odd
	 * 
	 * @return the value of t_bk_match_rmain.str_odd
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrOdd() {
		return strOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.str_odd
	 * 
	 * @param strOdd
	 *            the value for t_bk_match_rmain.str_odd
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrOdd(String strOdd) {
		this.strOdd = strOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.str_even
	 * 
	 * @return the value of t_bk_match_rmain.str_even
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrEven() {
		return strEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.str_even
	 * 
	 * @param strEven
	 *            the value for t_bk_match_rmain.str_even
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrEven(String strEven) {
		this.strEven = strEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_EOO
	 * 
	 * @return the value of t_bk_match_rmain.ior_EOO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorEoo() {
		return iorEoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_EOO
	 * 
	 * @param iorEoo
	 *            the value for t_bk_match_rmain.ior_EOO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorEoo(String iorEoo) {
		this.iorEoo = iorEoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_EOE
	 * 
	 * @return the value of t_bk_match_rmain.ior_EOE
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorEoe() {
		return iorEoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_EOE
	 * 
	 * @param iorEoe
	 *            the value for t_bk_match_rmain.ior_EOE
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorEoe(String iorEoe) {
		this.iorEoe = iorEoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_ouho
	 * 
	 * @return the value of t_bk_match_rmain.ratio_ouho
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuho() {
		return ratioOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_ouho
	 * 
	 * @param ratioOuho
	 *            the value for t_bk_match_rmain.ratio_ouho
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuho(String ratioOuho) {
		this.ratioOuho = ratioOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_ouhu
	 * 
	 * @return the value of t_bk_match_rmain.ratio_ouhu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuhu() {
		return ratioOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_ouhu
	 * 
	 * @param ratioOuhu
	 *            the value for t_bk_match_rmain.ratio_ouhu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuhu(String ratioOuhu) {
		this.ratioOuhu = ratioOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUHO
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUHO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuho() {
		return iorOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUHO
	 * 
	 * @param iorOuho
	 *            the value for t_bk_match_rmain.ior_OUHO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuho(String iorOuho) {
		this.iorOuho = iorOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUHU
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUHU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuhu() {
		return iorOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUHU
	 * 
	 * @param iorOuhu
	 *            the value for t_bk_match_rmain.ior_OUHU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuhu(String iorOuhu) {
		this.iorOuhu = iorOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_ouco
	 * 
	 * @return the value of t_bk_match_rmain.ratio_ouco
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuco() {
		return ratioOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_ouco
	 * 
	 * @param ratioOuco
	 *            the value for t_bk_match_rmain.ratio_ouco
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuco(String ratioOuco) {
		this.ratioOuco = ratioOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ratio_oucu
	 * 
	 * @return the value of t_bk_match_rmain.ratio_oucu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOucu() {
		return ratioOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ratio_oucu
	 * 
	 * @param ratioOucu
	 *            the value for t_bk_match_rmain.ratio_oucu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOucu(String ratioOucu) {
		this.ratioOucu = ratioOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUCO
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUCO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuco() {
		return iorOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUCO
	 * 
	 * @param iorOuco
	 *            the value for t_bk_match_rmain.ior_OUCO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuco(String iorOuco) {
		this.iorOuco = iorOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.ior_OUCU
	 * 
	 * @return the value of t_bk_match_rmain.ior_OUCU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOucu() {
		return iorOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.ior_OUCU
	 * 
	 * @param iorOucu
	 *            the value for t_bk_match_rmain.ior_OUCU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOucu(String iorOucu) {
		this.iorOucu = iorOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.more
	 * 
	 * @return the value of t_bk_match_rmain.more
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMore() {
		return more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.more
	 * 
	 * @param more
	 *            the value for t_bk_match_rmain.more
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMore(String more) {
		this.more = more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.eventid
	 * 
	 * @return the value of t_bk_match_rmain.eventid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getEventid() {
		return eventid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.eventid
	 * 
	 * @param eventid
	 *            the value for t_bk_match_rmain.eventid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setEventid(String eventid) {
		this.eventid = eventid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.hot
	 * 
	 * @return the value of t_bk_match_rmain.hot
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHot() {
		return hot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.hot
	 * 
	 * @param hot
	 *            the value for t_bk_match_rmain.hot
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHot(String hot) {
		this.hot = hot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.center_tv
	 * 
	 * @return the value of t_bk_match_rmain.center_tv
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getCenterTv() {
		return centerTv;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.center_tv
	 * 
	 * @param centerTv
	 *            the value for t_bk_match_rmain.center_tv
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setCenterTv(String centerTv) {
		this.centerTv = centerTv;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.play
	 * 
	 * @return the value of t_bk_match_rmain.play
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getPlay() {
		return play;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.play
	 * 
	 * @param play
	 *            the value for t_bk_match_rmain.play
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setPlay(String play) {
		this.play = play;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.gidm
	 * 
	 * @return the value of t_bk_match_rmain.gidm
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGidm() {
		return gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.gidm
	 * 
	 * @param gidm
	 *            the value for t_bk_match_rmain.gidm
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGidm(String gidm) {
		this.gidm = gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.isMaster
	 * 
	 * @return the value of t_bk_match_rmain.isMaster
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIsmaster() {
		return ismaster;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.isMaster
	 * 
	 * @param ismaster
	 *            the value for t_bk_match_rmain.isMaster
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIsmaster(String ismaster) {
		this.ismaster = ismaster;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.roll
	 * 
	 * @return the value of t_bk_match_rmain.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getRoll() {
		return roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.roll
	 * 
	 * @param roll
	 *            the value for t_bk_match_rmain.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRoll(Integer roll) {
		this.roll = roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.tmp1
	 * 
	 * @return the value of t_bk_match_rmain.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp1() {
		return tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.tmp1
	 * 
	 * @param tmp1
	 *            the value for t_bk_match_rmain.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.tmp2
	 * 
	 * @return the value of t_bk_match_rmain.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp2() {
		return tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.tmp2
	 * 
	 * @param tmp2
	 *            the value for t_bk_match_rmain.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_bk_match_rmain.tmp3
	 * 
	 * @return the value of t_bk_match_rmain.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp3() {
		return tmp3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_bk_match_rmain.tmp3
	 * 
	 * @param tmp3
	 *            the value for t_bk_match_rmain.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
}