package com.mh.entity;


import java.util.Date;

public class TFtMatchT {
	// 流水号
	// 自增长
	private Integer id;

	private String curtag;

	private Integer matchIndex;

	private Integer matchPage;

	private String timeType;

	private String gid;

	private String matchTime;

	private String league;

	private String gnumH;

	private String gnumC;

	private String teamH;

	private String teamC;

	private String strong;
	
	private String iorOdd;
	
	private String iorEven;
	
	private String iorT01;
	
	private String iorT23;
	
	private String iorT46;
	
	private String iorOver;

	private String iorMh;

	private String iorMc;

	private String iorMn;

	private Integer roll;

	private String tmp1;

	private String tmp2;

	private String tmp3;
	
	private Date modifyTime;

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.id
	 * 
	 * @param id
	 *            the value for t_ft_match_t.id
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.curTag
	 * 
	 * @return the value of t_ft_match_t.curTag
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getCurtag() {
		return curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.curTag
	 * 
	 * @param curtag
	 *            the value for t_ft_match_t.curTag
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.match_index
	 * 
	 * @return the value of t_ft_match_t.match_index
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchIndex() {
		return matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.match_index
	 * 
	 * @param matchIndex
	 *            the value for t_ft_match_t.match_index
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchIndex(Integer matchIndex) {
		this.matchIndex = matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.match_page
	 * 
	 * @return the value of t_ft_match_t.match_page
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchPage() {
		return matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.match_page
	 * 
	 * @param matchPage
	 *            the value for t_ft_match_t.match_page
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchPage(Integer matchPage) {
		this.matchPage = matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.time_type
	 * 
	 * @return the value of t_ft_match_t.time_type
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTimeType() {
		return timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.time_type
	 * 
	 * @param timeType
	 *            the value for t_ft_match_t.time_type
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.gid
	 * 
	 * @return the value of t_ft_match_t.gid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGid() {
		return gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.gid
	 * 
	 * @param gid
	 *            the value for t_ft_match_t.gid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.match_time
	 * 
	 * @return the value of t_ft_match_t.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMatchTime() {
		return matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.match_time
	 * 
	 * @param matchTime
	 *            the value for t_ft_match_t.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchTime(String matchTime) {
		this.matchTime = matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.league
	 * 
	 * @return the value of t_ft_match_t.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLeague() {
		return league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.league
	 * 
	 * @param league
	 *            the value for t_ft_match_t.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLeague(String league) {
		this.league = league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.gnum_h
	 * 
	 * @return the value of t_ft_match_t.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumH() {
		return gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.gnum_h
	 * 
	 * @param gnumH
	 *            the value for t_ft_match_t.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumH(String gnumH) {
		this.gnumH = gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.gnum_c
	 * 
	 * @return the value of t_ft_match_t.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumC() {
		return gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.gnum_c
	 * 
	 * @param gnumC
	 *            the value for t_ft_match_t.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumC(String gnumC) {
		this.gnumC = gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.team_h
	 * 
	 * @return the value of t_ft_match_t.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamH() {
		return teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.team_h
	 * 
	 * @param teamH
	 *            the value for t_ft_match_t.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamH(String teamH) {
		this.teamH = teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.team_c
	 * 
	 * @return the value of t_ft_match_t.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamC() {
		return teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.team_c
	 * 
	 * @param teamC
	 *            the value for t_ft_match_t.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamC(String teamC) {
		this.teamC = teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.strong
	 * 
	 * @return the value of t_ft_match_t.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrong() {
		return strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.strong
	 * 
	 * @param strong
	 *            the value for t_ft_match_t.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrong(String strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_ODD
	 * 
	 * @return the value of t_ft_match_t.ior_ODD
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOdd() {
		return iorOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_ODD
	 * 
	 * @param iorOdd
	 *            the value for t_ft_match_t.ior_ODD
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOdd(String iorOdd) {
		this.iorOdd = iorOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_EVEN
	 * 
	 * @return the value of t_ft_match_t.ior_EVEN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorEven() {
		return iorEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_EVEN
	 * 
	 * @param iorEven
	 *            the value for t_ft_match_t.ior_EVEN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorEven(String iorEven) {
		this.iorEven = iorEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_T01
	 * 
	 * @return the value of t_ft_match_t.ior_T01
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorT01() {
		return iorT01;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_T01
	 * 
	 * @param iorT01
	 *            the value for t_ft_match_t.ior_T01
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorT01(String iorT01) {
		this.iorT01 = iorT01;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_T23
	 * 
	 * @return the value of t_ft_match_t.ior_T23
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorT23() {
		return iorT23;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_T23
	 * 
	 * @param iorT23
	 *            the value for t_ft_match_t.ior_T23
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorT23(String iorT23) {
		this.iorT23 = iorT23;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_T46
	 * 
	 * @return the value of t_ft_match_t.ior_T46
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorT46() {
		return iorT46;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_T46
	 * 
	 * @param iorT46
	 *            the value for t_ft_match_t.ior_T46
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorT46(String iorT46) {
		this.iorT46 = iorT46;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_OVER
	 * 
	 * @return the value of t_ft_match_t.ior_OVER
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOver() {
		return iorOver;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_OVER
	 * 
	 * @param iorOver
	 *            the value for t_ft_match_t.ior_OVER
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOver(String iorOver) {
		this.iorOver = iorOver;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_MH
	 * 
	 * @return the value of t_ft_match_t.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMh() {
		return iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_MH
	 * 
	 * @param iorMh
	 *            the value for t_ft_match_t.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMh(String iorMh) {
		this.iorMh = iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_MC
	 * 
	 * @return the value of t_ft_match_t.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMc() {
		return iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_MC
	 * 
	 * @param iorMc
	 *            the value for t_ft_match_t.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMc(String iorMc) {
		this.iorMc = iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.ior_MN
	 * 
	 * @return the value of t_ft_match_t.ior_MN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMn() {
		return iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.ior_MN
	 * 
	 * @param iorMn
	 *            the value for t_ft_match_t.ior_MN
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMn(String iorMn) {
		this.iorMn = iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.roll
	 * 
	 * @return the value of t_ft_match_t.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getRoll() {
		return roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.roll
	 * 
	 * @param roll
	 *            the value for t_ft_match_t.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRoll(Integer roll) {
		this.roll = roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.tmp1
	 * 
	 * @return the value of t_ft_match_t.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp1() {
		return tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.tmp1
	 * 
	 * @param tmp1
	 *            the value for t_ft_match_t.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.tmp2
	 * 
	 * @return the value of t_ft_match_t.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp2() {
		return tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.tmp2
	 * 
	 * @param tmp2
	 *            the value for t_ft_match_t.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_ft_match_t.tmp3
	 * 
	 * @return the value of t_ft_match_t.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp3() {
		return tmp3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_ft_match_t.tmp3
	 * 
	 * @param tmp3
	 *            the value for t_ft_match_t.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
}