package com.mh.entity;


import java.io.Serializable;
import java.util.Date;
public class TFtMatchF implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String curtag;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer matchIndex;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer matchPage;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String timeType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String matchTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String league;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gnumH;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gnumC;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String teamH;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String teamC;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String strong;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FHH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFhh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FHN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFhn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FHC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFhc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FNH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFnh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FNN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFnn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FNC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFnc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FCH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFch;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FCN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFcn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.ior_FCC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorFcc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer roll;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_f.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp3;
	
	private Date modifyTime;
	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.id
	 * @return  the value of t_ft_match_f.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.id
	 * @param id  the value for t_ft_match_f.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.curTag
	 * @return  the value of t_ft_match_f.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getCurtag() {
		return curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.curTag
	 * @param curtag  the value for t_ft_match_f.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.match_index
	 * @return  the value of t_ft_match_f.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchIndex() {
		return matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.match_index
	 * @param matchIndex  the value for t_ft_match_f.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchIndex(Integer matchIndex) {
		this.matchIndex = matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.match_page
	 * @return  the value of t_ft_match_f.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchPage() {
		return matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.match_page
	 * @param matchPage  the value for t_ft_match_f.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchPage(Integer matchPage) {
		this.matchPage = matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.time_type
	 * @return  the value of t_ft_match_f.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTimeType() {
		return timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.time_type
	 * @param timeType  the value for t_ft_match_f.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.gid
	 * @return  the value of t_ft_match_f.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGid() {
		return gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.gid
	 * @param gid  the value for t_ft_match_f.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.match_time
	 * @return  the value of t_ft_match_f.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMatchTime() {
		return matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.match_time
	 * @param matchTime  the value for t_ft_match_f.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchTime(String matchTime) {
		this.matchTime = matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.league
	 * @return  the value of t_ft_match_f.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLeague() {
		return league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.league
	 * @param league  the value for t_ft_match_f.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLeague(String league) {
		this.league = league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.gnum_h
	 * @return  the value of t_ft_match_f.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumH() {
		return gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.gnum_h
	 * @param gnumH  the value for t_ft_match_f.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumH(String gnumH) {
		this.gnumH = gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.gnum_c
	 * @return  the value of t_ft_match_f.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumC() {
		return gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.gnum_c
	 * @param gnumC  the value for t_ft_match_f.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumC(String gnumC) {
		this.gnumC = gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.team_h
	 * @return  the value of t_ft_match_f.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamH() {
		return teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.team_h
	 * @param teamH  the value for t_ft_match_f.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamH(String teamH) {
		this.teamH = teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.team_c
	 * @return  the value of t_ft_match_f.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamC() {
		return teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.team_c
	 * @param teamC  the value for t_ft_match_f.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamC(String teamC) {
		this.teamC = teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.strong
	 * @return  the value of t_ft_match_f.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrong() {
		return strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.strong
	 * @param strong  the value for t_ft_match_f.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrong(String strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FHH
	 * @return  the value of t_ft_match_f.ior_FHH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFhh() {
		return iorFhh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FHH
	 * @param iorFhh  the value for t_ft_match_f.ior_FHH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFhh(String iorFhh) {
		this.iorFhh = iorFhh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FHN
	 * @return  the value of t_ft_match_f.ior_FHN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFhn() {
		return iorFhn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FHN
	 * @param iorFhn  the value for t_ft_match_f.ior_FHN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFhn(String iorFhn) {
		this.iorFhn = iorFhn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FHC
	 * @return  the value of t_ft_match_f.ior_FHC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFhc() {
		return iorFhc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FHC
	 * @param iorFhc  the value for t_ft_match_f.ior_FHC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFhc(String iorFhc) {
		this.iorFhc = iorFhc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FNH
	 * @return  the value of t_ft_match_f.ior_FNH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFnh() {
		return iorFnh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FNH
	 * @param iorFnh  the value for t_ft_match_f.ior_FNH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFnh(String iorFnh) {
		this.iorFnh = iorFnh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FNN
	 * @return  the value of t_ft_match_f.ior_FNN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFnn() {
		return iorFnn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FNN
	 * @param iorFnn  the value for t_ft_match_f.ior_FNN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFnn(String iorFnn) {
		this.iorFnn = iorFnn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FNC
	 * @return  the value of t_ft_match_f.ior_FNC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFnc() {
		return iorFnc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FNC
	 * @param iorFnc  the value for t_ft_match_f.ior_FNC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFnc(String iorFnc) {
		this.iorFnc = iorFnc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FCH
	 * @return  the value of t_ft_match_f.ior_FCH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFch() {
		return iorFch;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FCH
	 * @param iorFch  the value for t_ft_match_f.ior_FCH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFch(String iorFch) {
		this.iorFch = iorFch;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FCN
	 * @return  the value of t_ft_match_f.ior_FCN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFcn() {
		return iorFcn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FCN
	 * @param iorFcn  the value for t_ft_match_f.ior_FCN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFcn(String iorFcn) {
		this.iorFcn = iorFcn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.ior_FCC
	 * @return  the value of t_ft_match_f.ior_FCC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorFcc() {
		return iorFcc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.ior_FCC
	 * @param iorFcc  the value for t_ft_match_f.ior_FCC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorFcc(String iorFcc) {
		this.iorFcc = iorFcc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.roll
	 * @return  the value of t_ft_match_f.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getRoll() {
		return roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.roll
	 * @param roll  the value for t_ft_match_f.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRoll(Integer roll) {
		this.roll = roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.tmp1
	 * @return  the value of t_ft_match_f.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp1() {
		return tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.tmp1
	 * @param tmp1  the value for t_ft_match_f.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.tmp2
	 * @return  the value of t_ft_match_f.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp2() {
		return tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.tmp2
	 * @param tmp2  the value for t_ft_match_f.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_f.tmp3
	 * @return  the value of t_ft_match_f.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp3() {
		return tmp3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_f.tmp3
	 * @param tmp3  the value for t_ft_match_f.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
}