package com.mh.entity;


import java.util.Date;

public class TFtMatchP3 {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String curtag;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer matchIndex;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer matchPage;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String timeType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String matchTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String league;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gnumH;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gnumC;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String teamH;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String teamC;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String strong;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String ratio;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_PRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPrh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_PRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPrc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String ratioO;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String ratioU;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_POUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPouc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_POUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPouh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_PEOO
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPeoo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_PEOE
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorPeoe;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_MH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorMh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_MC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorMc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_MN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorMn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.hgid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String hgid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.hstrong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String hstrong;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.hratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String hratio;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HPRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHprh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HPRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHprc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.hratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String hratioO;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.hratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String hratioU;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HPOUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHpouh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HPOUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHpouc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HMH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHmh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HMC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.ior_HMN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String iorHmn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.more
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String more;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.gidm
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String gidm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.par_minlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String parMinlimit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.par_maxlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String parMaxlimit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private Integer roll;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_ft_match_p3.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	private String tmp3;
	
	
	private Date modifyTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.id
	 * @return  the value of t_ft_match_p3.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.id
	 * @param id  the value for t_ft_match_p3.id
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.curTag
	 * @return  the value of t_ft_match_p3.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getCurtag() {
		return curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.curTag
	 * @param curtag  the value for t_ft_match_p3.curTag
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.match_index
	 * @return  the value of t_ft_match_p3.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchIndex() {
		return matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.match_index
	 * @param matchIndex  the value for t_ft_match_p3.match_index
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchIndex(Integer matchIndex) {
		this.matchIndex = matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.match_page
	 * @return  the value of t_ft_match_p3.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchPage() {
		return matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.match_page
	 * @param matchPage  the value for t_ft_match_p3.match_page
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchPage(Integer matchPage) {
		this.matchPage = matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.time_type
	 * @return  the value of t_ft_match_p3.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTimeType() {
		return timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.time_type
	 * @param timeType  the value for t_ft_match_p3.time_type
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.gid
	 * @return  the value of t_ft_match_p3.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGid() {
		return gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.gid
	 * @param gid  the value for t_ft_match_p3.gid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.match_time
	 * @return  the value of t_ft_match_p3.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMatchTime() {
		return matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.match_time
	 * @param matchTime  the value for t_ft_match_p3.match_time
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchTime(String matchTime) {
		this.matchTime = matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.league
	 * @return  the value of t_ft_match_p3.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLeague() {
		return league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.league
	 * @param league  the value for t_ft_match_p3.league
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLeague(String league) {
		this.league = league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.gnum_h
	 * @return  the value of t_ft_match_p3.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumH() {
		return gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.gnum_h
	 * @param gnumH  the value for t_ft_match_p3.gnum_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumH(String gnumH) {
		this.gnumH = gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.gnum_c
	 * @return  the value of t_ft_match_p3.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumC() {
		return gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.gnum_c
	 * @param gnumC  the value for t_ft_match_p3.gnum_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumC(String gnumC) {
		this.gnumC = gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.team_h
	 * @return  the value of t_ft_match_p3.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamH() {
		return teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.team_h
	 * @param teamH  the value for t_ft_match_p3.team_h
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamH(String teamH) {
		this.teamH = teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.team_c
	 * @return  the value of t_ft_match_p3.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamC() {
		return teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.team_c
	 * @param teamC  the value for t_ft_match_p3.team_c
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamC(String teamC) {
		this.teamC = teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.strong
	 * @return  the value of t_ft_match_p3.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrong() {
		return strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.strong
	 * @param strong  the value for t_ft_match_p3.strong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrong(String strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ratio
	 * @return  the value of t_ft_match_p3.ratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatio() {
		return ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ratio
	 * @param ratio  the value for t_ft_match_p3.ratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatio(String ratio) {
		this.ratio = ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_PRH
	 * @return  the value of t_ft_match_p3.ior_PRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPrh() {
		return iorPrh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_PRH
	 * @param iorPrh  the value for t_ft_match_p3.ior_PRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPrh(String iorPrh) {
		this.iorPrh = iorPrh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_PRC
	 * @return  the value of t_ft_match_p3.ior_PRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPrc() {
		return iorPrc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_PRC
	 * @param iorPrc  the value for t_ft_match_p3.ior_PRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPrc(String iorPrc) {
		this.iorPrc = iorPrc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ratio_o
	 * @return  the value of t_ft_match_p3.ratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioO() {
		return ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ratio_o
	 * @param ratioO  the value for t_ft_match_p3.ratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioO(String ratioO) {
		this.ratioO = ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ratio_u
	 * @return  the value of t_ft_match_p3.ratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioU() {
		return ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ratio_u
	 * @param ratioU  the value for t_ft_match_p3.ratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioU(String ratioU) {
		this.ratioU = ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_POUC
	 * @return  the value of t_ft_match_p3.ior_POUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPouc() {
		return iorPouc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_POUC
	 * @param iorPouc  the value for t_ft_match_p3.ior_POUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPouc(String iorPouc) {
		this.iorPouc = iorPouc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_POUH
	 * @return  the value of t_ft_match_p3.ior_POUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPouh() {
		return iorPouh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_POUH
	 * @param iorPouh  the value for t_ft_match_p3.ior_POUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPouh(String iorPouh) {
		this.iorPouh = iorPouh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_PEOO
	 * @return  the value of t_ft_match_p3.ior_PEOO
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPeoo() {
		return iorPeoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_PEOO
	 * @param iorPeoo  the value for t_ft_match_p3.ior_PEOO
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPeoo(String iorPeoo) {
		this.iorPeoo = iorPeoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_PEOE
	 * @return  the value of t_ft_match_p3.ior_PEOE
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorPeoe() {
		return iorPeoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_PEOE
	 * @param iorPeoe  the value for t_ft_match_p3.ior_PEOE
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorPeoe(String iorPeoe) {
		this.iorPeoe = iorPeoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_MH
	 * @return  the value of t_ft_match_p3.ior_MH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMh() {
		return iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_MH
	 * @param iorMh  the value for t_ft_match_p3.ior_MH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMh(String iorMh) {
		this.iorMh = iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_MC
	 * @return  the value of t_ft_match_p3.ior_MC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMc() {
		return iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_MC
	 * @param iorMc  the value for t_ft_match_p3.ior_MC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMc(String iorMc) {
		this.iorMc = iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_MN
	 * @return  the value of t_ft_match_p3.ior_MN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMn() {
		return iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_MN
	 * @param iorMn  the value for t_ft_match_p3.ior_MN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMn(String iorMn) {
		this.iorMn = iorMn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.hgid
	 * @return  the value of t_ft_match_p3.hgid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHgid() {
		return hgid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.hgid
	 * @param hgid  the value for t_ft_match_p3.hgid
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHgid(String hgid) {
		this.hgid = hgid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.hstrong
	 * @return  the value of t_ft_match_p3.hstrong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHstrong() {
		return hstrong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.hstrong
	 * @param hstrong  the value for t_ft_match_p3.hstrong
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHstrong(String hstrong) {
		this.hstrong = hstrong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.hratio
	 * @return  the value of t_ft_match_p3.hratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHratio() {
		return hratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.hratio
	 * @param hratio  the value for t_ft_match_p3.hratio
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHratio(String hratio) {
		this.hratio = hratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HPRH
	 * @return  the value of t_ft_match_p3.ior_HPRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHprh() {
		return iorHprh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HPRH
	 * @param iorHprh  the value for t_ft_match_p3.ior_HPRH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHprh(String iorHprh) {
		this.iorHprh = iorHprh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HPRC
	 * @return  the value of t_ft_match_p3.ior_HPRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHprc() {
		return iorHprc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HPRC
	 * @param iorHprc  the value for t_ft_match_p3.ior_HPRC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHprc(String iorHprc) {
		this.iorHprc = iorHprc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.hratio_o
	 * @return  the value of t_ft_match_p3.hratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHratioO() {
		return hratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.hratio_o
	 * @param hratioO  the value for t_ft_match_p3.hratio_o
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHratioO(String hratioO) {
		this.hratioO = hratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.hratio_u
	 * @return  the value of t_ft_match_p3.hratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHratioU() {
		return hratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.hratio_u
	 * @param hratioU  the value for t_ft_match_p3.hratio_u
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHratioU(String hratioU) {
		this.hratioU = hratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HPOUH
	 * @return  the value of t_ft_match_p3.ior_HPOUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHpouh() {
		return iorHpouh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HPOUH
	 * @param iorHpouh  the value for t_ft_match_p3.ior_HPOUH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHpouh(String iorHpouh) {
		this.iorHpouh = iorHpouh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HPOUC
	 * @return  the value of t_ft_match_p3.ior_HPOUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHpouc() {
		return iorHpouc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HPOUC
	 * @param iorHpouc  the value for t_ft_match_p3.ior_HPOUC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHpouc(String iorHpouc) {
		this.iorHpouc = iorHpouc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HMH
	 * @return  the value of t_ft_match_p3.ior_HMH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHmh() {
		return iorHmh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HMH
	 * @param iorHmh  the value for t_ft_match_p3.ior_HMH
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHmh(String iorHmh) {
		this.iorHmh = iorHmh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HMC
	 * @return  the value of t_ft_match_p3.ior_HMC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHmc() {
		return iorHmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HMC
	 * @param iorHmc  the value for t_ft_match_p3.ior_HMC
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHmc(String iorHmc) {
		this.iorHmc = iorHmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.ior_HMN
	 * @return  the value of t_ft_match_p3.ior_HMN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorHmn() {
		return iorHmn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.ior_HMN
	 * @param iorHmn  the value for t_ft_match_p3.ior_HMN
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorHmn(String iorHmn) {
		this.iorHmn = iorHmn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.more
	 * @return  the value of t_ft_match_p3.more
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMore() {
		return more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.more
	 * @param more  the value for t_ft_match_p3.more
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMore(String more) {
		this.more = more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.gidm
	 * @return  the value of t_ft_match_p3.gidm
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGidm() {
		return gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.gidm
	 * @param gidm  the value for t_ft_match_p3.gidm
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGidm(String gidm) {
		this.gidm = gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.par_minlimit
	 * @return  the value of t_ft_match_p3.par_minlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getParMinlimit() {
		return parMinlimit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.par_minlimit
	 * @param parMinlimit  the value for t_ft_match_p3.par_minlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setParMinlimit(String parMinlimit) {
		this.parMinlimit = parMinlimit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.par_maxlimit
	 * @return  the value of t_ft_match_p3.par_maxlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getParMaxlimit() {
		return parMaxlimit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.par_maxlimit
	 * @param parMaxlimit  the value for t_ft_match_p3.par_maxlimit
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setParMaxlimit(String parMaxlimit) {
		this.parMaxlimit = parMaxlimit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.roll
	 * @return  the value of t_ft_match_p3.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getRoll() {
		return roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.roll
	 * @param roll  the value for t_ft_match_p3.roll
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRoll(Integer roll) {
		this.roll = roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.tmp1
	 * @return  the value of t_ft_match_p3.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp1() {
		return tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.tmp1
	 * @param tmp1  the value for t_ft_match_p3.tmp1
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.tmp2
	 * @return  the value of t_ft_match_p3.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp2() {
		return tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.tmp2
	 * @param tmp2  the value for t_ft_match_p3.tmp2
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_ft_match_p3.tmp3
	 * @return  the value of t_ft_match_p3.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp3() {
		return tmp3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_ft_match_p3.tmp3
	 * @param tmp3  the value for t_ft_match_p3.tmp3
	 * @abatorgenerated  Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
}