package com.mh.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


@Entity
@Table(name = "t_match_control")
public class TMatchControl implements java.io.Serializable {

 
	private static final long serialVersionUID = 1L;

	// 流水号
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	// 自增长
	@Column(name = "ID", nullable = false)
	private Integer id;
	 
	@Column(name = "time_type")
	private String timeType;
 
	@Column(name = "rtype")
	private String rtype;
 
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "curDate")
	private Date curdate;
 
	@Column(name = "curStatus")
	private Integer curstatus;
 
	@Column(name = "curCount")
	private Integer curcount;
 
	
	@Column(name = "curtag")
	private String curtag;
 
	
	@Column(name = "show_status")
	private Integer showStatus;
 
	@Column(name = "curpages")
	private Integer curpages;
 
	
	@Column(name = "name")
	private String name;
 
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time")
	private Date modifyTime;
	
	@Transient
	private Date successTime;
	
	@Transient
	private Integer version;

 
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.id
	 * @param id  the value for t_match_control.id
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.time_type
	 * @return  the value of t_match_control.time_type
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public String getTimeType() {
		return timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.time_type
	 * @param timeType  the value for t_match_control.time_type
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.rtype
	 * @return  the value of t_match_control.rtype
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public String getRtype() {
		return rtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.rtype
	 * @param rtype  the value for t_match_control.rtype
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setRtype(String rtype) {
		this.rtype = rtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.curDate
	 * @return  the value of t_match_control.curDate
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Date getCurdate() {
		return curdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.curDate
	 * @param curdate  the value for t_match_control.curDate
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setCurdate(Date curdate) {
		this.curdate = curdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.curStatus
	 * @return  the value of t_match_control.curStatus
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Integer getCurstatus() {
		return curstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.curStatus
	 * @param curstatus  the value for t_match_control.curStatus
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setCurstatus(Integer curstatus) {
		this.curstatus = curstatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.curCount
	 * @return  the value of t_match_control.curCount
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Integer getCurcount() {
		return curcount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.curCount
	 * @param curcount  the value for t_match_control.curCount
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setCurcount(Integer curcount) {
		this.curcount = curcount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.curTag
	 * @return  the value of t_match_control.curTag
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public String getCurtag() {
		return curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.curTag
	 * @param curtag  the value for t_match_control.curTag
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.show_status
	 * @return  the value of t_match_control.show_status
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Integer getShowStatus() {
		return showStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.show_status
	 * @param showStatus  the value for t_match_control.show_status
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setShowStatus(Integer showStatus) {
		this.showStatus = showStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.curPages
	 * @return  the value of t_match_control.curPages
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Integer getCurpages() {
		return curpages;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.curPages
	 * @param curpages  the value for t_match_control.curPages
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setCurpages(Integer curpages) {
		this.curpages = curpages;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.name
	 * @return  the value of t_match_control.name
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.name
	 * @param name  the value for t_match_control.name
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_match_control.modify_time
	 * @return  the value of t_match_control.modify_time
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_match_control.modify_time
	 * @param modifyTime  the value for t_match_control.modify_time
	 * @abatorgenerated  Sat Jan 10 03:50:17 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Date getSuccessTime() {
		return successTime;
	}

	public void setSuccessTime(Date successTime) {
		this.successTime = successTime;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
}