package com.mh.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Transient;

public class TRMatchRemain implements Serializable {

 
	private static final long serialVersionUID = 1L;

	// 流水号
	private Integer id;

	private String curtag;

	private Integer matchIndex;

	private Integer matchPage;
	private String gid;

	private String timer;

	private String league;

	private String gnumH;

	private String gnumC;

	private String teamH;

	private String teamC;

	private String strong;

	private String ratio;

	private String iorRh;

	private String iorRc;

	private String ratioO;

	private String ratioU;

	private String iorOuh;

	private String iorOuc;

	private String no1;

	private String no2;

	private String no3;

	private String scoreH;

	private String scoreC;

	private String no4;

	private String no5;

	private String no6;

	private String no7;

	private String no8;

	private String no9;

	private String no10;

	private String no11;

	private String no12;

	private String iorMh;

	private String iorMc;

	private String strOdd;

	private String strEven;

	private String iorEoo;

	private String iorEoe;

	private String ratioOuho;

	private String ratioOuhu;

	private String iorOuho;

	private String iorOuhu;

	private String ratioOuco;

	private String ratioOucu;

	private String iorOuco;

	private String iorOucu;
	private String eventid;

	private String hot;

	private String centerTv;

	private String play;
	private String matchTime;

	private String retimeset;

	private String more;

	private String gidm;

	private String ismaster;

	private String nowsession;

	private String scoreh;

	private String scorec;

	private String lastgoal;

	private String lasttime;

	private Integer roll;

	private String tmp1;

	private String tmp2;

	private String tmp3;
	
	private Date modifyTime;
	
	
	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Transient
	private String frasherDate;
	
	
	

	public String getFrasherDate() {
		return frasherDate;
	}

	public void setFrasherDate(String frasherDate) {
		this.frasherDate = frasherDate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCurtag() {
		return curtag;
	}

	public void setCurtag(String curtag) {
		this.curtag = curtag;
	}

	public Integer getMatchIndex() {
		return matchIndex;
	}

	public void setMatchIndex(Integer matchIndex) {
		this.matchIndex = matchIndex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.match_page
	 * 
	 * @return the value of t_r_match_remain.match_page
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getMatchPage() {
		return matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.match_page
	 * 
	 * @param matchPage
	 *            the value for t_r_match_remain.match_page
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchPage(Integer matchPage) {
		this.matchPage = matchPage;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.gid
	 * 
	 * @return the value of t_r_match_remain.gid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGid() {
		return gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.gid
	 * 
	 * @param gid
	 *            the value for t_r_match_remain.gid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGid(String gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.timer
	 * 
	 * @return the value of t_r_match_remain.timer
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTimer() {
		return timer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.timer
	 * 
	 * @param timer
	 *            the value for t_r_match_remain.timer
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTimer(String timer) {
		this.timer = timer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.league
	 * 
	 * @return the value of t_r_match_remain.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLeague() {
		return league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.league
	 * 
	 * @param league
	 *            the value for t_r_match_remain.league
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLeague(String league) {
		this.league = league;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.gnum_h
	 * 
	 * @return the value of t_r_match_remain.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumH() {
		return gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.gnum_h
	 * 
	 * @param gnumH
	 *            the value for t_r_match_remain.gnum_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumH(String gnumH) {
		this.gnumH = gnumH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.gnum_c
	 * 
	 * @return the value of t_r_match_remain.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGnumC() {
		return gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.gnum_c
	 * 
	 * @param gnumC
	 *            the value for t_r_match_remain.gnum_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGnumC(String gnumC) {
		this.gnumC = gnumC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.team_h
	 * 
	 * @return the value of t_r_match_remain.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamH() {
		return teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.team_h
	 * 
	 * @param teamH
	 *            the value for t_r_match_remain.team_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamH(String teamH) {
		this.teamH = teamH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.team_c
	 * 
	 * @return the value of t_r_match_remain.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTeamC() {
		return teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.team_c
	 * 
	 * @param teamC
	 *            the value for t_r_match_remain.team_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTeamC(String teamC) {
		this.teamC = teamC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.strong
	 * 
	 * @return the value of t_r_match_remain.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrong() {
		return strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.strong
	 * 
	 * @param strong
	 *            the value for t_r_match_remain.strong
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrong(String strong) {
		this.strong = strong;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio
	 * 
	 * @return the value of t_r_match_remain.ratio
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatio() {
		return ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio
	 * 
	 * @param ratio
	 *            the value for t_r_match_remain.ratio
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatio(String ratio) {
		this.ratio = ratio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_RH
	 * 
	 * @return the value of t_r_match_remain.ior_RH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorRh() {
		return iorRh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_RH
	 * 
	 * @param iorRh
	 *            the value for t_r_match_remain.ior_RH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorRh(String iorRh) {
		this.iorRh = iorRh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_RC
	 * 
	 * @return the value of t_r_match_remain.ior_RC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorRc() {
		return iorRc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_RC
	 * 
	 * @param iorRc
	 *            the value for t_r_match_remain.ior_RC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorRc(String iorRc) {
		this.iorRc = iorRc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_o
	 * 
	 * @return the value of t_r_match_remain.ratio_o
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioO() {
		return ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_o
	 * 
	 * @param ratioO
	 *            the value for t_r_match_remain.ratio_o
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioO(String ratioO) {
		this.ratioO = ratioO;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_u
	 * 
	 * @return the value of t_r_match_remain.ratio_u
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioU() {
		return ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_u
	 * 
	 * @param ratioU
	 *            the value for t_r_match_remain.ratio_u
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioU(String ratioU) {
		this.ratioU = ratioU;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUH
	 * 
	 * @return the value of t_r_match_remain.ior_OUH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuh() {
		return iorOuh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUH
	 * 
	 * @param iorOuh
	 *            the value for t_r_match_remain.ior_OUH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuh(String iorOuh) {
		this.iorOuh = iorOuh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUC
	 * 
	 * @return the value of t_r_match_remain.ior_OUC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuc() {
		return iorOuc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUC
	 * 
	 * @param iorOuc
	 *            the value for t_r_match_remain.ior_OUC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuc(String iorOuc) {
		this.iorOuc = iorOuc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no1
	 * 
	 * @return the value of t_r_match_remain.no1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo1() {
		return no1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no1
	 * 
	 * @param no1
	 *            the value for t_r_match_remain.no1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo1(String no1) {
		this.no1 = no1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no2
	 * 
	 * @return the value of t_r_match_remain.no2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo2() {
		return no2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no2
	 * 
	 * @param no2
	 *            the value for t_r_match_remain.no2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo2(String no2) {
		this.no2 = no2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no3
	 * 
	 * @return the value of t_r_match_remain.no3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo3() {
		return no3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no3
	 * 
	 * @param no3
	 *            the value for t_r_match_remain.no3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo3(String no3) {
		this.no3 = no3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.score_h
	 * 
	 * @return the value of t_r_match_remain.score_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getScoreH() {
		return scoreH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.score_h
	 * 
	 * @param scoreH
	 *            the value for t_r_match_remain.score_h
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setScoreH(String scoreH) {
		this.scoreH = scoreH;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.score_c
	 * 
	 * @return the value of t_r_match_remain.score_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getScoreC() {
		return scoreC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.score_c
	 * 
	 * @param scoreC
	 *            the value for t_r_match_remain.score_c
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setScoreC(String scoreC) {
		this.scoreC = scoreC;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no4
	 * 
	 * @return the value of t_r_match_remain.no4
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo4() {
		return no4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no4
	 * 
	 * @param no4
	 *            the value for t_r_match_remain.no4
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo4(String no4) {
		this.no4 = no4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no5
	 * 
	 * @return the value of t_r_match_remain.no5
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo5() {
		return no5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no5
	 * 
	 * @param no5
	 *            the value for t_r_match_remain.no5
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo5(String no5) {
		this.no5 = no5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no6
	 * 
	 * @return the value of t_r_match_remain.no6
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo6() {
		return no6;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no6
	 * 
	 * @param no6
	 *            the value for t_r_match_remain.no6
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo6(String no6) {
		this.no6 = no6;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no7
	 * 
	 * @return the value of t_r_match_remain.no7
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo7() {
		return no7;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no7
	 * 
	 * @param no7
	 *            the value for t_r_match_remain.no7
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo7(String no7) {
		this.no7 = no7;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no8
	 * 
	 * @return the value of t_r_match_remain.no8
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo8() {
		return no8;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no8
	 * 
	 * @param no8
	 *            the value for t_r_match_remain.no8
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo8(String no8) {
		this.no8 = no8;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no9
	 * 
	 * @return the value of t_r_match_remain.no9
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo9() {
		return no9;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no9
	 * 
	 * @param no9
	 *            the value for t_r_match_remain.no9
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo9(String no9) {
		this.no9 = no9;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no10
	 * 
	 * @return the value of t_r_match_remain.no10
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo10() {
		return no10;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no10
	 * 
	 * @param no10
	 *            the value for t_r_match_remain.no10
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo10(String no10) {
		this.no10 = no10;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no11
	 * 
	 * @return the value of t_r_match_remain.no11
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo11() {
		return no11;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no11
	 * 
	 * @param no11
	 *            the value for t_r_match_remain.no11
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo11(String no11) {
		this.no11 = no11;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.no12
	 * 
	 * @return the value of t_r_match_remain.no12
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNo12() {
		return no12;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.no12
	 * 
	 * @param no12
	 *            the value for t_r_match_remain.no12
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNo12(String no12) {
		this.no12 = no12;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_MH
	 * 
	 * @return the value of t_r_match_remain.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMh() {
		return iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_MH
	 * 
	 * @param iorMh
	 *            the value for t_r_match_remain.ior_MH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMh(String iorMh) {
		this.iorMh = iorMh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_MC
	 * 
	 * @return the value of t_r_match_remain.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorMc() {
		return iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_MC
	 * 
	 * @param iorMc
	 *            the value for t_r_match_remain.ior_MC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorMc(String iorMc) {
		this.iorMc = iorMc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.str_odd
	 * 
	 * @return the value of t_r_match_remain.str_odd
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrOdd() {
		return strOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.str_odd
	 * 
	 * @param strOdd
	 *            the value for t_r_match_remain.str_odd
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrOdd(String strOdd) {
		this.strOdd = strOdd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.str_even
	 * 
	 * @return the value of t_r_match_remain.str_even
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getStrEven() {
		return strEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.str_even
	 * 
	 * @param strEven
	 *            the value for t_r_match_remain.str_even
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setStrEven(String strEven) {
		this.strEven = strEven;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_EOO
	 * 
	 * @return the value of t_r_match_remain.ior_EOO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorEoo() {
		return iorEoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_EOO
	 * 
	 * @param iorEoo
	 *            the value for t_r_match_remain.ior_EOO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorEoo(String iorEoo) {
		this.iorEoo = iorEoo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_EOE
	 * 
	 * @return the value of t_r_match_remain.ior_EOE
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorEoe() {
		return iorEoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_EOE
	 * 
	 * @param iorEoe
	 *            the value for t_r_match_remain.ior_EOE
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorEoe(String iorEoe) {
		this.iorEoe = iorEoe;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_ouho
	 * 
	 * @return the value of t_r_match_remain.ratio_ouho
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuho() {
		return ratioOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_ouho
	 * 
	 * @param ratioOuho
	 *            the value for t_r_match_remain.ratio_ouho
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuho(String ratioOuho) {
		this.ratioOuho = ratioOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_ouhu
	 * 
	 * @return the value of t_r_match_remain.ratio_ouhu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuhu() {
		return ratioOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_ouhu
	 * 
	 * @param ratioOuhu
	 *            the value for t_r_match_remain.ratio_ouhu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuhu(String ratioOuhu) {
		this.ratioOuhu = ratioOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUHO
	 * 
	 * @return the value of t_r_match_remain.ior_OUHO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuho() {
		return iorOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUHO
	 * 
	 * @param iorOuho
	 *            the value for t_r_match_remain.ior_OUHO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuho(String iorOuho) {
		this.iorOuho = iorOuho;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUHU
	 * 
	 * @return the value of t_r_match_remain.ior_OUHU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuhu() {
		return iorOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUHU
	 * 
	 * @param iorOuhu
	 *            the value for t_r_match_remain.ior_OUHU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuhu(String iorOuhu) {
		this.iorOuhu = iorOuhu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_ouco
	 * 
	 * @return the value of t_r_match_remain.ratio_ouco
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOuco() {
		return ratioOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_ouco
	 * 
	 * @param ratioOuco
	 *            the value for t_r_match_remain.ratio_ouco
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOuco(String ratioOuco) {
		this.ratioOuco = ratioOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ratio_oucu
	 * 
	 * @return the value of t_r_match_remain.ratio_oucu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRatioOucu() {
		return ratioOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ratio_oucu
	 * 
	 * @param ratioOucu
	 *            the value for t_r_match_remain.ratio_oucu
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRatioOucu(String ratioOucu) {
		this.ratioOucu = ratioOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUCO
	 * 
	 * @return the value of t_r_match_remain.ior_OUCO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOuco() {
		return iorOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUCO
	 * 
	 * @param iorOuco
	 *            the value for t_r_match_remain.ior_OUCO
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOuco(String iorOuco) {
		this.iorOuco = iorOuco;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.ior_OUCU
	 * 
	 * @return the value of t_r_match_remain.ior_OUCU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIorOucu() {
		return iorOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.ior_OUCU
	 * 
	 * @param iorOucu
	 *            the value for t_r_match_remain.ior_OUCU
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIorOucu(String iorOucu) {
		this.iorOucu = iorOucu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.eventid
	 * 
	 * @return the value of t_r_match_remain.eventid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getEventid() {
		return eventid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.eventid
	 * 
	 * @param eventid
	 *            the value for t_r_match_remain.eventid
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setEventid(String eventid) {
		this.eventid = eventid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.hot
	 * 
	 * @return the value of t_r_match_remain.hot
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getHot() {
		return hot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.hot
	 * 
	 * @param hot
	 *            the value for t_r_match_remain.hot
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setHot(String hot) {
		this.hot = hot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.center_tv
	 * 
	 * @return the value of t_r_match_remain.center_tv
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getCenterTv() {
		return centerTv;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.center_tv
	 * 
	 * @param centerTv
	 *            the value for t_r_match_remain.center_tv
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setCenterTv(String centerTv) {
		this.centerTv = centerTv;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.play
	 * 
	 * @return the value of t_r_match_remain.play
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getPlay() {
		return play;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.play
	 * 
	 * @param play
	 *            the value for t_r_match_remain.play
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setPlay(String play) {
		this.play = play;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.match_time
	 * 
	 * @return the value of t_r_match_remain.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMatchTime() {
		return matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.match_time
	 * 
	 * @param matchTime
	 *            the value for t_r_match_remain.match_time
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMatchTime(String matchTime) {
		this.matchTime = matchTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.retimeset
	 * 
	 * @return the value of t_r_match_remain.retimeset
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getRetimeset() {
		return retimeset;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.retimeset
	 * 
	 * @param retimeset
	 *            the value for t_r_match_remain.retimeset
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRetimeset(String retimeset) {
		this.retimeset = retimeset;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.more
	 * 
	 * @return the value of t_r_match_remain.more
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getMore() {
		return more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.more
	 * 
	 * @param more
	 *            the value for t_r_match_remain.more
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setMore(String more) {
		this.more = more;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.gidm
	 * 
	 * @return the value of t_r_match_remain.gidm
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getGidm() {
		return gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.gidm
	 * 
	 * @param gidm
	 *            the value for t_r_match_remain.gidm
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setGidm(String gidm) {
		this.gidm = gidm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.isMaster
	 * 
	 * @return the value of t_r_match_remain.isMaster
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getIsmaster() {
		return ismaster;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.isMaster
	 * 
	 * @param ismaster
	 *            the value for t_r_match_remain.isMaster
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setIsmaster(String ismaster) {
		this.ismaster = ismaster;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.nowSession
	 * 
	 * @return the value of t_r_match_remain.nowSession
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getNowsession() {
		return nowsession;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.nowSession
	 * 
	 * @param nowsession
	 *            the value for t_r_match_remain.nowSession
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setNowsession(String nowsession) {
		this.nowsession = nowsession;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.scoreH
	 * 
	 * @return the value of t_r_match_remain.scoreH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getScoreh() {
		return scoreh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.scoreH
	 * 
	 * @param scoreh
	 *            the value for t_r_match_remain.scoreH
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setScoreh(String scoreh) {
		this.scoreh = scoreh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.scoreC
	 * 
	 * @return the value of t_r_match_remain.scoreC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getScorec() {
		return scorec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.scoreC
	 * 
	 * @param scorec
	 *            the value for t_r_match_remain.scoreC
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setScorec(String scorec) {
		this.scorec = scorec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.lastGoal
	 * 
	 * @return the value of t_r_match_remain.lastGoal
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLastgoal() {
		return lastgoal;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.lastGoal
	 * 
	 * @param lastgoal
	 *            the value for t_r_match_remain.lastGoal
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLastgoal(String lastgoal) {
		this.lastgoal = lastgoal;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.lastTime
	 * 
	 * @return the value of t_r_match_remain.lastTime
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getLasttime() {
		return lasttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.lastTime
	 * 
	 * @param lasttime
	 *            the value for t_r_match_remain.lastTime
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setLasttime(String lasttime) {
		this.lasttime = lasttime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.roll
	 * 
	 * @return the value of t_r_match_remain.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public Integer getRoll() {
		return roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.roll
	 * 
	 * @param roll
	 *            the value for t_r_match_remain.roll
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setRoll(Integer roll) {
		this.roll = roll;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.tmp1
	 * 
	 * @return the value of t_r_match_remain.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp1() {
		return tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.tmp1
	 * 
	 * @param tmp1
	 *            the value for t_r_match_remain.tmp1
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.tmp2
	 * 
	 * @return the value of t_r_match_remain.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp2() {
		return tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.tmp2
	 * 
	 * @param tmp2
	 *            the value for t_r_match_remain.tmp2
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_r_match_remain.tmp3
	 * 
	 * @return the value of t_r_match_remain.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public String getTmp3() {
		return tmp3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_r_match_remain.tmp3
	 * 
	 * @param tmp3
	 *            the value for t_r_match_remain.tmp3
	 * @abatorgenerated Sat Apr 04 09:38:29 CST 2015
	 */
	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}
}